### PR TITLE
Implement AST Parsing

### PR DESCRIPTION
**Pull request by mkaminski1988**
@crocodele Just wanted to give you an early heads up that I've started implementing the AST approach that I've put off for years. :^)

Right now it's not 100% feature complete:

```
Number of tests :  116               115
Tests skipped   :    1 (  0.9%) --------
Tests warned    :    2 (  1.7%) (  1.7%)
Tests failed    :   21 ( 18.1%) ( 18.3%)
Expected fail   :    6 (  5.2%) (  5.2%)
Tests passed    :   86 ( 74.1%) ( 74.8%)
```

Two of the tests that you marked as XFAIL are now passing:

```
=====================================================================
WARNED TEST SUMMARY
---------------------------------------------------------------------
Test bracket notation with wildcard on array [tests/comparison_bracket_notation/038.phpt] (warn: XFAIL section but test passes)
Test bracket notation with wildcard on null value array [tests/comparison_bracket_notation/041.phpt] (warn: XFAIL section but test passes)
=====================================================================
```

### CODE REVIEW

**Comment by crocodele** [comment]
@mkaminski1988, that's great news! :tada:

Btw, I'm on the last chapter of the book you recommended – very good read indeed.

**Comment by mkaminski1988** [comment]
> @mkaminski1988, that's great news! 🎉
> 
> Btw, I'm on the last chapter of the book you recommended – very good read indeed.

Glad you enjoyed the recco! Hopefully you can apply your learnings to future improvements of the extension.

I'm almost done with the refactoring. Currently 97/116 tests are passing.

**Comment by crocodele** [comment]
> I'm almost done with the refactoring. Currently 97/116 tests are passing.

And now even closer I see. :slightly_smiling_face: Fantastic – looking forward to merging this!

I have a branch for the filter expression tests from JSONPath Comparison, about halfway done now. Those tests basically all fail at the moment, perhaps because they apply filtering on the first level (e.g. `$[?(@.key==42)]`) and not on a node? Anyway, I won't make any code changes to the current implementation.

**Comment by mkaminski1988** [comment]
Yikes, I see what you mean. Here are the results before and after merging into my feature branch:

```bash
Before merge

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   65
---------------------------------------------------------------------

Number of tests :  116               115
Tests skipped   :    1 (  0.9%) --------
Tests warned    :    3 (  2.6%) (  2.6%)
Tests failed    :    4 (  3.4%) (  3.5%)
Expected fail   :    5 (  4.3%) (  4.3%)
Tests passed    :  103 ( 88.8%) ( 89.6%)
---------------------------------------------------------------------
Time taken      :    8 seconds
=====================================================================

After merge
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   65
---------------------------------------------------------------------

Number of tests :  200               198
Tests skipped   :    2 (  1.0%) --------
Tests warned    :   14 (  7.0%) (  7.1%)
Tests failed    :    5 (  2.5%) (  2.5%)
Expected fail   :   44 ( 22.0%) ( 22.2%)
Tests passed    :  135 ( 67.5%) ( 68.2%)
---------------------------------------------------------------------
Time taken      :  194 seconds
=====================================================================
```

On the bright side, 11 additional "expected failures" are passing post-merge. I haven't looked at all the tests, but it seems like there is a lot of low hanging fruit. Once I complete the AST feature (in the next couple days), perhaps we can break up the work on completing the expected failures?

**Comment by crocodele** [comment]
Yup, sounds good!

**Comment by crocodele** [comment]
Also, many tests especially in the filter expressions section deal with quite crazy cases for which there's no clear right or wrong outcome, and for which different JSONPath implementations return widely different results. :man_shrugging:

**Comment by mkaminski1988** [comment]
Interesting. Is there a particular grammar that represents your requirements? I've been loosely following [this one](https://github.com/Galbar/JsonPath-PHP#jsonpath-language).

**Comment by crocodele** [comment]
> Is there a particular grammar that represents your requirements?

No, not really. For the [JSONPath Comparison tests](https://cburgmer.github.io/json-path-comparison/) that have a consensus result, I've used that. For the ones without consensus, I've mostly followed Proposal A (grammar [here](https://github.com/cburgmer/json-path-comparison/tree/master/proposals/Proposal_A#grammar)), but on a few occasions something else when the proposal felt odd.

Point being, the expected results that I've defined for the tests shouldn't be regarded as the single truth. We might want to throw exceptions for some cases that now expect a result array, and vice versa, depending on what we can and want to support.

One of the weirdest case I've seen is [set comparison](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_set_wise_comparison_to_set.html), with `$.x[?(@[*]>=$.y[*])]` as the path. To me that feels like taking things a couple of steps too far, but apparently at least one library supports that. :smile:

**Comment by crocodele** [comment]
Thank you! Awesome work! :bowing_man:

**Comment by mkaminski1988** [comment]
Thanks!

BTW, I added a debug mode that displays lex tokens and the contents of the AST.

Just do:
```
make clean; EXTRA_CFLAGS="-DJSONPATH_DEBUG" make
```

Note that this will break the unit tests. It's more for debugging one-off JSONpath expressions.

**Pull request merged**
